services:
  server:
    build:
      context: ./server
    ports:
      - "3080:3080"
    volumes:
      - ./server:/server
      - /server/node_modules
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./client:/client
      - /client/node_modules
